"""Added Permissions, Groups, Users

Revision ID: 8e95f85d7f22
Revises: 
Create Date: 2017-12-28 21:53:20.154628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e95f85d7f22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('perm_type', sa.String(length=30), nullable=False),
    sa.Column('column_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.id'], )
    )
    op.create_table('User_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('groups_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groups_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_groups')
    op.drop_table('Group_permissions')
    op.drop_table('Users')
    op.drop_table('Permissions')
    op.drop_table('Groups')
    # ### end Alembic commands ###
